name: CI             

on: [push, pull_request]   # запускать при любом push и при каждом PR

jobs:
  test-and-build:
    runs-on: ubuntu-latest     

    steps:
      # Шаг 1 — вытащить код
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 2 — установить Python 3.12
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # Шаг 3 — поставить зависимости и запустить pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run unit tests
        run: pytest -q          

      # Шаг 4 — собрать Docker-образ
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .            # текущий каталог = корень репо
          push: false           # пока не публикуем образ во внешний реестр
          tags: local/demo:latest
